### ISSUE TITLE
create basic docker-compose file

### ISSUE THREAD

**Issue by svd01** [svd01/Project#5]
Prepare basic docker-composite file-sharing on the database and the application

version: '2'

services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always

**Comment by rkhozinov** [comment]
it should be done in code

**Comment by rkhozinov** [comment]
docker-compose
